//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 05:56:47 PM IST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getMCMPStatusResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getMCMPStatusResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SynapseMessage" type="{http://xmlns3.bayer.com/ProcessedMCMPService}synapseResponseMessage" minOccurs="0" form="qualified"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMCMPStatusResponse", propOrder = {
    "synapseMessage"
})
public class GetMCMPStatusResponse {

    @XmlElement(name = "SynapseMessage", namespace = "http://xmlns3.bayer.com/ProcessedMCMPService")
    protected SynapseResponseMessage synapseMessage;

    /**
     * Gets the value of the synapseMessage property.
     * 
     * @return
     *     possible object is
     *     {@link SynapseResponseMessage }
     *     
     */
    public SynapseResponseMessage getSynapseMessage() {
        return synapseMessage;
    }

    /**
     * Sets the value of the synapseMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynapseResponseMessage }
     *     
     */
    public void setSynapseMessage(SynapseResponseMessage value) {
        this.synapseMessage = value;
    }

}
