//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 05:56:47 PM IST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mcmpRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mcmpRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaterialDescriptionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MaterialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MCMP_ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MCMPMappingID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LifecyclePhase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mcmpRecord", propOrder = {
    "materialDescriptionName",
    "materialNumber",
    "mcmpErrorMessage",
    "mcmpMappingID",
    "lifecyclePhase"
})
public class McmpRecord {

    @XmlElement(name = "MaterialDescriptionName")
    protected String materialDescriptionName;
    @XmlElement(name = "MaterialNumber")
    protected String materialNumber;
    @XmlElement(name = "MCMP_ErrorMessage")
    protected String mcmpErrorMessage;
    @XmlElement(name = "MCMPMappingID")
    protected String mcmpMappingID;
    @XmlElement(name = "LifecyclePhase")
    protected String lifecyclePhase;

    /**
     * Gets the value of the materialDescriptionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialDescriptionName() {
        return materialDescriptionName;
    }

    /**
     * Sets the value of the materialDescriptionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialDescriptionName(String value) {
        this.materialDescriptionName = value;
    }

    /**
     * Gets the value of the materialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialNumber() {
        return materialNumber;
    }

    /**
     * Sets the value of the materialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialNumber(String value) {
        this.materialNumber = value;
    }

    /**
     * Gets the value of the mcmpErrorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCMPErrorMessage() {
        return mcmpErrorMessage;
    }

    /**
     * Sets the value of the mcmpErrorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCMPErrorMessage(String value) {
        this.mcmpErrorMessage = value;
    }

    /**
     * Gets the value of the mcmpMappingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCMPMappingID() {
        return mcmpMappingID;
    }

    /**
     * Sets the value of the mcmpMappingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCMPMappingID(String value) {
        this.mcmpMappingID = value;
    }

    /**
     * Gets the value of the lifecyclePhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifecyclePhase() {
        return lifecyclePhase;
    }

    /**
     * Sets the value of the lifecyclePhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifecyclePhase(String value) {
        this.lifecyclePhase = value;
    }

}
