//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 05:56:47 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns3.bayer.com/ProcessedMCMPService")
package com.example.howtodoinjava.schemas.school;
